excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://welyntonoliveira.github.io
title: Welynton - Blog
email: oliveirawelynton@gmail.com
author: Welynton Oliveira
description: Olá! Como vai? Prazer! Eu me chamo Welynton, sou um profissional de Design de interface, apesar de ser formado em Análise Desenvolvimento de Sistemas. Mas o que realmente me desperta interesse são as interfaces e interações cada vez mais humanizadas entre o computador e o seres humanos. Tenho experiência em e-commerce, agora estou pronto para novos desafios e oportunidades, creio que aqui será a minha porta de entrada. Aqui falarei de Design, Negócios no meio digital, minhas experiências e claro dos meus projetos. Então não perca nada seguindo meu blog. Obrigado pela visita!
paginate: 3
google_analytics:77657667-1 
